[device.Keithley2400]
baudrate = 9600
timeout = 10000

[device.Keithley2400.measurement]
source_mode = "CURR"
sense_mode = "VOLT"
current_range = 10e-6
voltage_range = 10
current_level = 5e-6
voltage_level = 5
compliance_voltage = 15
compliance_current = 12e-6
measurevolt_range = 10
measurecurrent_range = 1e-2
